Repository Albeoris/Memoria, pull requests merged in 2024-04, with the labels that each got.

#349 PSX font, Mod support, bugfixes
  Assembly-CSharp/Global/Field/Map/Actor/FieldMapActorController.cs
  Assembly-CSharp/Global/Field/Map/FieldMap.cs
  Assembly-CSharp/Global/Field/Map/NarrowMapList.cs
  Assembly-CSharp/Global/Game/GameOverUI.cs
  Assembly-CSharp/Global/TitleUI.cs
  Assembly-CSharp/Global/UI/UIRoot.cs
  Assembly-CSharp/Global/UI/UIStretch.cs
  Assembly-CSharp/Global/World/WorldHUD.cs
  Assembly-CSharp/Global/ff9/ff9.cs
  Memoria.MSBuild/BuildEnvironment.cs
  Memoria.MSBuild/Pack.cs
  Memoria.Patcher/FF9_Data/EmbeddedAsset/FA/p_fa.mpc
  Memoria.Patcher/GameInfo/GameLocationInfo.cs
  Memoria.Patcher/Memoria.Patcher.csproj
  README.md
  References/Memoria.MSBuild.dll
Labels: Screen size 🖥️, Font ✒️

#350 Widescreen fixes + code simplification/debug
  Assembly-CSharp/Assets/Sources/Graphics/Movie/MovieMaterial.cs
  Assembly-CSharp/Global/BGCAM_DEF.cs
  Assembly-CSharp/Global/EBG_ATTACH_DEF.cs
  Assembly-CSharp/Global/Field/Map/FieldMap.cs
  Assembly-CSharp/Global/Field/Map/NarrowMapList.cs
  Assembly-CSharp/Global/Honolulu/HonoluluFieldMain.cs
  Assembly-CSharp/Global/MBG.cs
Labels: Screen size 🖥️

#317 New Audio Backend (SoLoud)
  Assembly-CSharp/Assembly-CSharp.csproj
  Assembly-CSharp/Assets/Sources/Graphics/Movie/MovieMaterial.cs
  Assembly-CSharp/Global/AllSoundDispatchPlayer.cs
  Assembly-CSharp/Global/ISd/ISdLibAPI.cs
  Assembly-CSharp/Global/ISd/ISdLibAPIProxy.cs
  Assembly-CSharp/Global/SFX/SfxSoundPlayer.cs
  Assembly-CSharp/Global/Sd/SdLibAPIWithProLicense.cs
  Assembly-CSharp/Global/Sound/Lib/SoundLib.cs
  Assembly-CSharp/Global/Sound/Loader/SoundImporter.cs
  Assembly-CSharp/Global/Sound/Loader/SoundLoaderDocumentDirectory.cs
  Assembly-CSharp/Global/Sound/Loader/SoundLoaderResources.cs
  Assembly-CSharp/Global/Sound/Loader/SoundLoaderStreamingAssets.cs
  Assembly-CSharp/Global/Sound/MusicPlayer.cs
  Assembly-CSharp/Global/Sound/SoLoud/Bus.cs
  Assembly-CSharp/Global/Sound/SoLoud/Queue.cs
  Assembly-CSharp/Global/Sound/SoLoud/SdLibAPIWithSoloud.cs
  Assembly-CSharp/Global/Sound/SoLoud/Soloud.cs
  Assembly-CSharp/Global/Sound/SoLoud/WavStream.cs
  Assembly-CSharp/Global/Sound/SoLoud/x64/soloud.dll
  Assembly-CSharp/Global/Sound/SoLoud/x86/soloud.dll
  Assembly-CSharp/Global/Sound/SoundPlayer.cs
  Assembly-CSharp/Memoria/Configuration/Access/Audio.cs
  Assembly-CSharp/Memoria/Configuration/Structure/AudioSection.cs
  Assembly-CSharp/Memoria/VoiceActing/VoicePlayer.cs
  Memoria.Launcher/Ini/Memoria.ini
  Memoria.MSBuild/Pack.cs
  Memoria.Prime/OggFile/AKB2/AKB2Header.cs
  References/Memoria.MSBuild.dll
Labels: Sound 🔊
